// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: Roberto Valenti and the Holons contributors
//
// The shift PLAN: a holon's catalog of recurring shifts and the rules that
// turn it into concrete occurrences and, against the live schedule, into
// "what is missing". Pure — no network, no signing, no store; the store I/O
// for the plan itself is the two small functions at the bottom.
//
// The catalog mirrors Elinor's (src/shifts.js there): the same seeds, the
// same validation, the same code generator, so a plan edited on a kiosk and
// one edited in Elinor's Mini App describe the same schedule. Elinor runs
// every enabled shift every day; `days` is the one extension.

import type { ShiftDefinition, ShiftOccurrence, ShiftPlan, ShiftRsvp } from './types.js';
import { enrolledPubkeys, isValidShiftCode, shiftAddress, shiftDTag, type ShiftIdentityMap } from './protocol.js';

/** Elinor's default capacity per shift. */
export const DEFAULT_SHIFT_CAPACITY = 2;
/** Elinor materialises two weeks ahead. */
export const DEFAULT_HORIZON_DAYS = 14;
/** Key of the plan on the holon's `settings` record. */
export const SHIFT_PLAN_KEY = 'shifts';

/** Elinor's seed catalog — what a fresh plan starts from. */
export const DEFAULT_SHIFT_DEFINITIONS: readonly ShiftDefinition[] = Object.freeze([
  { code: 'mc', title: 'Morning Cleaning', start: '08:30', end: '10:30', capacity: DEFAULT_SHIFT_CAPACITY, enabled: true },
  { code: 'lp', title: 'Lunch Preparation', start: '10:30', end: '12:30', capacity: DEFAULT_SHIFT_CAPACITY, enabled: true },
  { code: 'lc', title: 'Lunch Cleaning', start: '14:00', end: '16:00', capacity: DEFAULT_SHIFT_CAPACITY, enabled: true },
  { code: 'dp', title: 'Dinner Preparation', start: '16:30', end: '18:30', capacity: DEFAULT_SHIFT_CAPACITY, enabled: true },
  { code: 'dc', title: 'Dinner Cleaning', start: '20:30', end: '22:30', capacity: DEFAULT_SHIFT_CAPACITY, enabled: true },
].map((d) => Object.freeze({ ...d })));

const TIME_RE = /^([01]\d|2[0-3]):[0-5]\d$/;
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

/** A fresh plan: Elinor's seeds in the given zone. */
export function defaultShiftPlan(tzid = 'UTC', location?: string): ShiftPlan {
  return {
    tzid,
    ...(location ? { location } : {}),
    horizonDays: DEFAULT_HORIZON_DAYS,
    shifts: DEFAULT_SHIFT_DEFINITIONS.map((d) => ({ ...d })),
  };
}

/** True when `tzid` is a zone this runtime can format in. */
export function isValidTimeZone(tzid: string): boolean {
  try {
    new Intl.DateTimeFormat('en-US', { timeZone: tzid });
    return true;
  } catch {
    return false;
  }
}

export type ShiftDefinitionInput = Partial<ShiftDefinition> & { title?: unknown };

/**
 * Elinor's `validateDef`, field for field, plus `days`/`location`. Returns
 * the clean definition or a human-readable error. The code is validated when
 * given and generated by `upsertShiftDefinition` when not.
 */
export function validateShiftDefinition(
  input: ShiftDefinitionInput,
): { ok: true; value: Omit<ShiftDefinition, 'code'> & { code?: string } } | { ok: false; error: string } {
  const title = String(input.title ?? '').trim();
  if (!title || title.length > 40) return { ok: false, error: 'Title must be 1–40 characters.' };
  const start = String(input.start ?? '');
  const end = String(input.end ?? '');
  if (!TIME_RE.test(start) || !TIME_RE.test(end)) return { ok: false, error: 'Times must be HH:MM (24h).' };
  if (start >= end) return { ok: false, error: 'End time must be after start time.' };
  const capacity = Number(input.capacity ?? DEFAULT_SHIFT_CAPACITY);
  if (!Number.isInteger(capacity) || capacity < 1 || capacity > 20) {
    return { ok: false, error: 'People needed must be 1–20.' };
  }
  const description = String(input.description ?? '').trim().slice(0, 300);
  const code = input.code === undefined || input.code === '' ? undefined : String(input.code);
  if (code !== undefined && !isValidShiftCode(code)) return { ok: false, error: 'Invalid shift code.' };
  let days: number[] | undefined;
  if (Array.isArray(input.days) && input.days.length) {
    days = [...new Set(input.days.map(Number))].filter((d) => Number.isInteger(d) && d >= 1 && d <= 7).sort();
    if (!days.length) return { ok: false, error: 'Days must be ISO weekdays 1–7.' };
    if (days.length === 7) days = undefined; // every day is the default
  }
  const location = String(input.location ?? '').trim().slice(0, 80);
  return {
    ok: true,
    value: {
      ...(code !== undefined ? { code } : {}),
      title,
      start,
      end,
      capacity,
      enabled: input.enabled === undefined ? true : Boolean(input.enabled),
      ...(description ? { description } : {}),
      ...(days ? { days } : {}),
      ...(location ? { location } : {}),
    },
  };
}

/** Elinor's `genCode`: initials of the title, disambiguated against the catalog. */
export function generateShiftCode(title: string, taken: Iterable<string>): string {
  const used = new Set(taken);
  let base = title
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .trim()
    .split(/\s+/)
    .map((w) => w[0])
    .join('')
    .slice(0, 8);
  if (base.length < 2) base = title.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 4) || 'shift';
  let code = base;
  let i = 2;
  while (used.has(code)) code = `${base}${i++}`;
  return code;
}

/**
 * Add or replace one definition, returning the new plan and the code it
 * landed on. Unknown codes on an edit are an error, so a stale form cannot
 * resurrect a removed shift under its old code by accident.
 */
export function upsertShiftDefinition(
  plan: ShiftPlan,
  input: ShiftDefinitionInput,
): { ok: true; plan: ShiftPlan; code: string; created: boolean } | { ok: false; error: string } {
  const v = validateShiftDefinition(input);
  if (!v.ok) return v;
  const codes = plan.shifts.map((s) => s.code);
  const created = v.value.code === undefined;
  const code = v.value.code ?? generateShiftCode(v.value.title, codes);
  const idx = codes.indexOf(code);
  if (!created && idx < 0) return { ok: false, error: 'Unknown shift.' };
  const def: ShiftDefinition = { ...v.value, code };
  const shifts = idx < 0 ? [...plan.shifts, def] : plan.shifts.map((s, i) => (i === idx ? def : s));
  return { ok: true, plan: { ...plan, shifts: sortDefinitions(shifts) }, code, created: idx < 0 };
}

/** Drop a definition from the catalog. Removing an unknown code is a no-op. */
export function removeShiftDefinition(plan: ShiftPlan, code: string): ShiftPlan {
  return { ...plan, shifts: plan.shifts.filter((s) => s.code !== code) };
}

/** Elinor's ordering: by start time, then code. */
export function sortDefinitions(shifts: ShiftDefinition[]): ShiftDefinition[] {
  return [...shifts].sort((a, b) => a.start.localeCompare(b.start) || a.code.localeCompare(b.code));
}

// ---------------------------------------------------------------------------
// Time — DST-safe wall-clock → unix, the way Elinor's time.js does it
// ---------------------------------------------------------------------------

function tzOffsetMs(tzid: string, at: Date): number {
  const dtf = new Intl.DateTimeFormat('en-US', {
    timeZone: tzid,
    hour12: false,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
  const p: Record<string, string> = {};
  for (const part of dtf.formatToParts(at)) p[part.type] = part.value;
  const asUtc = Date.UTC(+p.year, +p.month - 1, +p.day, +p.hour % 24, +p.minute, +p.second);
  return asUtc - at.getTime();
}

/** `YYYY-MM-DD` + `HH:MM` in `tzid` → unix seconds. */
export function localToUnix(date: string, time: string, tzid: string): number {
  const [y, m, d] = date.split('-').map(Number);
  const [hh, mm] = time.split(':').map(Number);
  let guess = Date.UTC(y, m - 1, d, hh, mm);
  for (let i = 0; i < 2; i++) guess = Date.UTC(y, m - 1, d, hh, mm) - tzOffsetMs(tzid, new Date(guess));
  return Math.floor(guess / 1000);
}

/** Today's `YYYY-MM-DD` in `tzid`. */
export function todayIn(tzid: string, now: Date = new Date()): string {
  return new Intl.DateTimeFormat('en-CA', { timeZone: tzid, year: 'numeric', month: '2-digit', day: '2-digit' }).format(now);
}

export function addDays(date: string, n: number): string {
  const [y, m, d] = date.split('-').map(Number);
  return new Date(Date.UTC(y, m - 1, d + n, 12)).toISOString().slice(0, 10);
}

/** ISO weekday (1 = Monday … 7 = Sunday) of a `YYYY-MM-DD`. */
export function isoWeekday(date: string): number {
  const [y, m, d] = date.split('-').map(Number);
  const dow = new Date(Date.UTC(y, m - 1, d, 12)).getUTCDay();
  return dow === 0 ? 7 : dow;
}

export function isValidDate(date: string): boolean {
  return DATE_RE.test(date) && !Number.isNaN(Date.parse(`${date}T12:00:00Z`));
}

// ---------------------------------------------------------------------------
// Materialisation
// ---------------------------------------------------------------------------

/** A slot the plan says should exist on a given day. */
export interface ExpectedShift {
  date: string;
  code: string;
  dTag: string;
  definition: ShiftDefinition;
  title: string;
  /** Unix seconds. */
  start: number;
  end: number;
  tzid: string;
  location?: string;
  capacity: number;
  description?: string;
  /** Wall-clock `HH:MM–HH:MM`, for the derived content. */
  timeRange: string;
}

/** Whether a definition runs on a date. */
export function runsOn(def: Pick<ShiftDefinition, 'enabled' | 'days'>, date: string): boolean {
  if (!def.enabled) return false;
  if (!def.days?.length) return true;
  return def.days.includes(isoWeekday(date));
}

/** One expected slot, or null when the definition does not run that day. */
export function expectedShift(plan: ShiftPlan, def: ShiftDefinition, groupId: string, date: string): ExpectedShift | null {
  if (!runsOn(def, date)) return null;
  const location = def.location ?? plan.location;
  return {
    date,
    code: def.code,
    dTag: shiftDTag({ groupId, date, code: def.code }),
    definition: def,
    title: def.title,
    start: localToUnix(date, def.start, plan.tzid),
    end: localToUnix(date, def.end, plan.tzid),
    tzid: plan.tzid,
    ...(location ? { location } : {}),
    capacity: def.capacity,
    ...(def.description ? { description: def.description } : {}),
    timeRange: `${def.start}–${def.end}`,
  };
}

/**
 * Every slot the plan expects from `fromDate` for `days` days — the set the
 * coordinator materialises, in date then start order.
 */
export function expectedShifts(plan: ShiftPlan, groupId: string, fromDate: string, days = plan.horizonDays): ExpectedShift[] {
  const out: ExpectedShift[] = [];
  for (let i = 0; i < days; i++) {
    const date = addDays(fromDate, i);
    for (const def of sortDefinitions(plan.shifts)) {
      const e = expectedShift(plan, def, groupId, date);
      if (e) out.push(e);
    }
  }
  return out;
}

/** `HH:MM` wall-clock of a unix instant in `tzid`. */
export function wallClock(unixSeconds: number, tzid: string): string {
  try {
    return new Intl.DateTimeFormat('en-GB', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone: tzid }).format(
      new Date(unixSeconds * 1000),
    );
  } catch {
    return new Date(unixSeconds * 1000).toISOString().slice(11, 16);
  }
}

/**
 * Adopt a plan from what is already on the wall: one definition per code,
 * taken from the newest occurrence carrying it (its title, wall-clock
 * times in the zone it was published in, capacity, location). This is how
 * a holon whose shifts Elinor has been publishing gets a plan that matches
 * them, instead of a seed catalog that marks every one of them stale.
 * Returns null when there is nothing to adopt.
 */
export function planFromOccurrences(occurrences: ShiftOccurrence[], fallbackTzid = 'UTC'): ShiftPlan | null {
  if (!occurrences.length) return null;
  const newest = new Map<string, ShiftOccurrence>();
  for (const o of occurrences) {
    const prev = newest.get(o.code);
    if (!prev || o.createdAt > prev.createdAt || (o.createdAt === prev.createdAt && o.start > prev.start)) {
      newest.set(o.code, o);
    }
  }
  // The zone: whatever most occurrences were published in.
  const zones = new Map<string, number>();
  for (const o of occurrences) if (o.startTzid && isValidTimeZone(o.startTzid)) zones.set(o.startTzid, (zones.get(o.startTzid) ?? 0) + 1);
  const tzid = [...zones.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? fallbackTzid;
  // The location: the one most occurrences carry; a definition only keeps
  // its own when it differs.
  const places = new Map<string, number>();
  for (const o of occurrences) if (o.location) places.set(o.location, (places.get(o.location) ?? 0) + 1);
  const location = [...places.entries()].sort((a, b) => b[1] - a[1])[0]?.[0];
  const shifts: ShiftDefinition[] = [];
  for (const o of newest.values()) {
    const v = validateShiftDefinition({
      code: o.code,
      title: o.title,
      start: wallClock(o.start, tzid),
      end: wallClock(o.end, tzid),
      capacity: o.capacity ?? DEFAULT_SHIFT_CAPACITY,
      enabled: true,
      ...(o.location && o.location !== location ? { location: o.location } : {}),
    });
    if (v.ok) shifts.push({ ...v.value, code: o.code });
  }
  if (!shifts.length) return null;
  return { tzid, ...(location ? { location } : {}), horizonDays: DEFAULT_HORIZON_DAYS, shifts: sortDefinitions(shifts) };
}

// ---------------------------------------------------------------------------
// Reconciliation — the plan against the live schedule
// ---------------------------------------------------------------------------

/**
 *  - `unpublished`: the plan expects it, no occurrence is on the relay yet.
 *  - `unstaffed`:   published, nobody on it.
 *  - `short`:       published, some people, still below capacity.
 *  - `covered`:     published and at (or over) capacity.
 *  - `open`:        published with no capacity — never "missing".
 *  - `stale`:       published, but the plan no longer expects it.
 */
export type ShiftCoverageState = 'unpublished' | 'unstaffed' | 'short' | 'covered' | 'open' | 'stale';

export interface ShiftCoverage {
  key: string;
  date: string;
  code: string;
  state: ShiftCoverageState;
  expected?: ExpectedShift;
  occurrence?: ShiftOccurrence;
  /** People enrolled (persons, with an identity map). */
  enrolled: string[];
  /** Spots still open, 0 when full or when the shift has no capacity. */
  missing: number;
  /**
   * The published occurrence disagrees with the plan (time, title, place or
   * capacity) — a republish would bring it in line.
   */
  drifted: boolean;
}

export interface ShiftCoverageSummary {
  /** Slots the plan expects in the window. */
  expected: number;
  unpublished: number;
  unstaffed: number;
  short: number;
  covered: number;
  stale: number;
  /** Spots still open across every published shift in the window. */
  spotsOpen: number;
  /** Spots filled across every published shift with a capacity. */
  spotsFilled: number;
  spotsTotal: number;
}

/** Coverage state of one published occurrence on its own (no plan). */
export function coverageOf(
  occurrence: ShiftOccurrence,
  rsvps: Iterable<ShiftRsvp>,
  identity?: ShiftIdentityMap,
): Pick<ShiftCoverage, 'state' | 'enrolled' | 'missing'> {
  const enrolled = enrolledPubkeys(occurrence, rsvps, identity);
  if (occurrence.capacity === undefined) return { state: 'open', enrolled, missing: 0 };
  const missing = Math.max(0, occurrence.capacity - enrolled.length);
  const state: ShiftCoverageState = enrolled.length === 0 && missing > 0 ? 'unstaffed' : missing > 0 ? 'short' : 'covered';
  return { state, enrolled, missing };
}

function drifts(e: ExpectedShift, o: ShiftOccurrence): boolean {
  return (
    e.start !== o.start ||
    e.end !== o.end ||
    e.title !== o.title ||
    e.capacity !== o.capacity ||
    (e.location ?? '') !== (o.location ?? '')
  );
}

/**
 * Line the plan's expected slots up against what is published and who is
 * on it. Occurrences from a coordinator other than `coordinatorPubkey`
 * (when given) are ignored, so a foreign 31923 never counts as ours.
 */
export function reconcileSchedule(
  expected: ExpectedShift[],
  occurrences: ShiftOccurrence[],
  rsvps: Iterable<ShiftRsvp>,
  opts: { identity?: ShiftIdentityMap; coordinatorPubkey?: string; window?: { since?: number; until?: number } } = {},
): { items: ShiftCoverage[]; summary: ShiftCoverageSummary } {
  const rsvpList = [...rsvps];
  const coord = opts.coordinatorPubkey?.toLowerCase();
  const inWindow = (start: number, end: number) =>
    (opts.window?.since === undefined || end >= opts.window.since) &&
    (opts.window?.until === undefined || start <= opts.window.until);
  const byKey = new Map<string, ShiftOccurrence>();
  for (const o of occurrences) {
    if (coord && o.pubkey.toLowerCase() !== coord) continue;
    if (!inWindow(o.start, o.end)) continue;
    byKey.set(`${o.date}-${o.code}`, o);
  }
  const items: ShiftCoverage[] = [];
  const seen = new Set<string>();
  for (const e of expected) {
    if (!inWindow(e.start, e.end)) continue;
    const key = `${e.date}-${e.code}`;
    seen.add(key);
    const occ = byKey.get(key);
    if (!occ) {
      items.push({ key, date: e.date, code: e.code, state: 'unpublished', expected: e, enrolled: [], missing: e.capacity, drifted: false });
      continue;
    }
    const c = coverageOf(occ, rsvpList, opts.identity);
    items.push({ key, date: e.date, code: e.code, ...c, expected: e, occurrence: occ, drifted: drifts(e, occ) });
  }
  for (const [key, occ] of byKey) {
    if (seen.has(key)) continue;
    const c = coverageOf(occ, rsvpList, opts.identity);
    items.push({ key, date: occ.date, code: occ.code, ...c, state: 'stale', occurrence: occ, drifted: false });
  }
  items.sort((a, b) => {
    const sa = a.expected?.start ?? a.occurrence?.start ?? 0;
    const sb = b.expected?.start ?? b.occurrence?.start ?? 0;
    return sa - sb || a.code.localeCompare(b.code);
  });
  const summary: ShiftCoverageSummary = {
    expected: items.filter((i) => i.expected).length,
    unpublished: 0,
    unstaffed: 0,
    short: 0,
    covered: 0,
    stale: 0,
    spotsOpen: 0,
    spotsFilled: 0,
    spotsTotal: 0,
  };
  for (const i of items) {
    if (i.state === 'unpublished') summary.unpublished++;
    else if (i.state === 'stale') summary.stale++;
    else if (i.state === 'unstaffed') summary.unstaffed++;
    else if (i.state === 'short') summary.short++;
    else if (i.state === 'covered') summary.covered++;
    if (i.occurrence?.capacity !== undefined) {
      summary.spotsOpen += i.missing;
      summary.spotsFilled += Math.min(i.enrolled.length, i.occurrence.capacity);
      summary.spotsTotal += i.occurrence.capacity;
    }
  }
  return { items, summary };
}

/** The address a coordinator's occurrence for an expected slot would have. */
export function expectedAddress(coordinatorPubkey: string, e: Pick<ExpectedShift, 'dTag'>): string {
  return shiftAddress(coordinatorPubkey, e.dTag);
}

// ---------------------------------------------------------------------------
// Persistence — the plan on the holon's settings record
// ---------------------------------------------------------------------------

/** Store shape the plan I/O needs (the kiosk's ReaStore, a HoloSphere, …). */
export interface ShiftPlanStore {
  get(holon: string, lens: string, key?: string): Promise<unknown>;
  put(holon: string, lens: string, value: unknown): Promise<unknown>;
}

function cleanDefinition(raw: unknown): ShiftDefinition | null {
  if (!raw || typeof raw !== 'object') return null;
  const r = raw as Record<string, unknown>;
  const code = String(r.code ?? '');
  if (!isValidShiftCode(code)) return null;
  const v = validateShiftDefinition({ ...(r as ShiftDefinitionInput), code });
  return v.ok ? { ...v.value, code } : null;
}

/**
 * The plan on a settings record, or null when none is stored. Malformed
 * definitions are dropped rather than failing the whole plan, so one bad
 * hand edit cannot blank a board.
 */
export function readShiftPlan(settings: unknown): ShiftPlan | null {
  const doc = Array.isArray(settings) ? settings.find((e) => e && typeof e === 'object' && SHIFT_PLAN_KEY in e) : settings;
  const raw = doc && typeof doc === 'object' ? (doc as Record<string, unknown>)[SHIFT_PLAN_KEY] : undefined;
  if (!raw || typeof raw !== 'object') return null;
  const p = raw as Record<string, unknown>;
  const tzid = typeof p.tzid === 'string' && isValidTimeZone(p.tzid) ? p.tzid : 'UTC';
  const horizon = Number(p.horizonDays);
  const shifts = Array.isArray(p.shifts)
    ? p.shifts.map(cleanDefinition).filter((d): d is ShiftDefinition => d !== null)
    : [];
  const location = typeof p.location === 'string' && p.location.trim() ? p.location.trim() : undefined;
  return {
    tzid,
    ...(location ? { location } : {}),
    horizonDays: Number.isInteger(horizon) && horizon >= 1 && horizon <= 60 ? horizon : DEFAULT_HORIZON_DAYS,
    shifts: sortDefinitions(shifts),
  };
}

/** Strip a plan to what is stored (no undefined fields — Holosphere warns on those). */
export function normalizeShiftPlan(plan: ShiftPlan): ShiftPlan {
  const tzid = isValidTimeZone(plan.tzid) ? plan.tzid : 'UTC';
  const horizon = Number(plan.horizonDays);
  const shifts = sortDefinitions(
    plan.shifts.map(cleanDefinition).filter((d): d is ShiftDefinition => d !== null),
  );
  const location = plan.location?.trim();
  return {
    tzid,
    ...(location ? { location } : {}),
    horizonDays: Number.isInteger(horizon) && horizon >= 1 && horizon <= 60 ? horizon : DEFAULT_HORIZON_DAYS,
    shifts,
  };
}

/** Load the holon's plan from its settings record. */
export async function loadShiftPlan(store: Pick<ShiftPlanStore, 'get'>, holonId: string): Promise<ShiftPlan | null> {
  let existing: unknown = null;
  try {
    existing = await store.get(String(holonId), 'settings', String(holonId));
  } catch {
    // Unreadable settings read as "no plan".
  }
  return readShiftPlan(existing);
}

/**
 * Write the plan onto the settings record, preserving every other field
 * (allocation, name, …) the way the flows settings writer does.
 */
export async function saveShiftPlan(store: ShiftPlanStore, holonId: string, plan: ShiftPlan): Promise<ShiftPlan> {
  let existing: unknown = null;
  try {
    existing = await store.get(String(holonId), 'settings', String(holonId));
  } catch {
    // A missing record is created below.
  }
  const doc = Array.isArray(existing)
    ? (existing.find((e) => e && typeof e === 'object' && (e as { id?: unknown }).id === String(holonId)) ?? {})
    : existing && typeof existing === 'object'
      ? existing
      : {};
  const clean = normalizeShiftPlan(plan);
  await store.put(String(holonId), 'settings', {
    ...(doc as object),
    id: String(holonId),
    [SHIFT_PLAN_KEY]: clean,
  });
  return clean;
}
